package ru.contextguide.campaign.textCampaign;


public enum TextCampaignSettingsGetEnum {
    ADD_METRICA_TAG,
    ADD_OPENSTAT_TAG,
    ADD_TO_FAVORITES,
    DAILY_BUDGET_ALLOWED,
    ENABLE_AREA_OF_INTEREST_TARGETING,
    ENABLE_AUTOFOCUS,
    ENABLE_BEHAVIORAL_TARGETING,
    ENABLE_EXTENDED_AD_TITLE,
    ENABLE_RELATED_KEYWORDS,
    ENABLE_SITE_MONITORING,
    EXCLUDE_PAUSED_COMPETING_ADS,
    MAINTAIN_NETWORK_CPC,
    REQUIRE_SERVICING,
    SHARED_ACCOUNT_ENABLED
}
