package ru.contextguide.campaign.textCampaign;

/**
 * Тип стратегии показа на поиске:
 */
public enum TextCampaignSearchStrategyTypeEnum {
    AVERAGE_CPA, AVERAGE_ROI, AVERAGE_CPC, HIGHEST_POSITION, IMPRESSIONS_BELOW_SEARCH, LOWEST_COST, LOWEST_COST_GUARANTEE, LOWEST_COST_PREMIUM, SERVING_OFF, UNKNOWN, WB_MAXIMUM_CLICKS, WB_MAXIMUM_CONVERSION_RATE, WEEKLY_CLICK_PACKAGE
}